name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write # required to create a github release
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
